"""add customer portal access

Revision ID: 601b2d5be580
Revises: 7f3a9c4d1e20
Create Date: 2026-08-11 23:21:01.790949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '601b2d5be580'
down_revision: Union[str, Sequence[str], None] = '7f3a9c4d1e20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('username', sa.String(length=60), nullable=True))
    op.add_column('customer', sa.Column('password_hash', sa.String(length=255), nullable=True))
    op.add_column('customer', sa.Column('portal_active', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.create_index(op.f('ix_customer_username'), 'customer', ['username'], unique=True)
    # Pre-existing drift from the prior migration's batch_alter_table recreate:
    # 'shipment.inquiry_id' is model-declared unique-only (no plain index), but
    # the old non-unique index from the original schema was never dropped.
    op.drop_index(op.f('ix_shipment_inquiry_id'), table_name='shipment')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_shipment_inquiry_id'), 'shipment', ['inquiry_id'], unique=False)
    op.drop_index(op.f('ix_customer_username'), table_name='customer')
    op.drop_column('customer', 'portal_active')
    op.drop_column('customer', 'password_hash')
    op.drop_column('customer', 'username')
    # ### end Alembic commands ###
