"""add worker areas

Revision ID: 37acfec25a45
Revises: 9158bf1bec4b
Create Date: 2026-08-11 01:57:09.226201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37acfec25a45'
down_revision: Union[str, Sequence[str], None] = '9158bf1bec4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('area',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('stage', sa.Enum('INQUIRY', 'QUOTED', 'JOB_OPENED', 'DOCS_FILED', 'PICKED_UP', 'IN_TRANSIT', 'CUSTOMS_CLEARANCE', 'ARRIVED', 'DELIVERED', name='shipmentstage', native_enum=False, length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stage')
    )
    op.create_table('worker',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('username', sa.String(length=60), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['area.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_worker_area_id'), 'worker', ['area_id'], unique=False)
    op.create_index(op.f('ix_worker_username'), 'worker', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_worker_username'), table_name='worker')
    op.drop_index(op.f('ix_worker_area_id'), table_name='worker')
    op.drop_table('worker')
    op.drop_table('area')
    # ### end Alembic commands ###
