"""initial schema

Revision ID: 9158bf1bec4b
Revises: 
Create Date: 2026-08-11 00:22:58.707634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9158bf1bec4b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_email'), 'customer', ['email'], unique=True)
    op.create_table('job_number_counter',
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('last_value', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('year')
    )
    op.create_table('rate_card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('origin', sa.String(length=120), nullable=False),
    sa.Column('destination', sa.String(length=120), nullable=False),
    sa.Column('mode', sa.Enum('AIR', 'SEA', 'ROAD', name='transportmode', native_enum=False, length=30), nullable=False),
    sa.Column('carrier', sa.String(length=120), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_until', sa.Date(), nullable=False),
    sa.Column('minimum_charge', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_rate_card_lane_mode_validity', 'rate_card', ['origin', 'destination', 'mode', 'valid_from', 'valid_until'], unique=False)
    op.create_table('inquiry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('origin', sa.String(length=120), nullable=False),
    sa.Column('destination', sa.String(length=120), nullable=False),
    sa.Column('mode', sa.Enum('AIR', 'SEA', 'ROAD', name='transportmode', native_enum=False, length=30), nullable=False),
    sa.Column('cargo_type', sa.String(length=120), nullable=False),
    sa.Column('weight_kg', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('volume_cbm', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('dimensions', sa.String(length=200), nullable=True),
    sa.Column('ready_date', sa.Date(), nullable=True),
    sa.Column('incoterm', sa.String(length=10), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inquiry_customer_id'), 'inquiry', ['customer_id'], unique=False)
    op.create_index('ix_inquiry_lane_mode', 'inquiry', ['origin', 'destination', 'mode'], unique=False)
    op.create_table('rate_card_break',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rate_card_id', sa.Integer(), nullable=False),
    sa.Column('min_weight', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('max_weight', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('min_volume', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('max_volume', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('unit', sa.Enum('PER_KG', 'PER_CBM', 'FLAT', name='unitofmeasure', native_enum=False, length=30), nullable=False),
    sa.Column('rate', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.CheckConstraint('max_volume IS NULL OR max_volume > min_volume', name='ck_break_volume_range'),
    sa.CheckConstraint('max_weight IS NULL OR max_weight > min_weight', name='ck_break_weight_range'),
    sa.ForeignKeyConstraint(['rate_card_id'], ['rate_card.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rate_card_break_rate_card_id'), 'rate_card_break', ['rate_card_id'], unique=False)
    op.create_table('rate_card_charge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rate_card_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('FREIGHT', 'DOCUMENTATION', 'CUSTOMS', 'PICKUP', 'HANDLING', 'OTHER', name='chargekind', native_enum=False, length=30), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('basis', sa.Enum('FLAT', 'PER_KG', 'PERCENT_OF_FREIGHT', name='chargebasis', native_enum=False, length=30), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['rate_card_id'], ['rate_card.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rate_card_charge_rate_card_id'), 'rate_card_charge', ['rate_card_id'], unique=False)
    op.create_table('quote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inquiry_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SENT', 'ACCEPTED', 'EXPIRED', name='quotestatus', native_enum=False, length=30), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('markup_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('valid_until', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['inquiry_id'], ['inquiry.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quote_inquiry_id'), 'quote', ['inquiry_id'], unique=False)
    op.create_table('quote_line_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quote_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('FREIGHT', 'DOCUMENTATION', 'CUSTOMS', 'PICKUP', 'HANDLING', 'OTHER', name='chargekind', native_enum=False, length=30), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('calculated_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('final_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('markup_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_manual_override', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['quote_id'], ['quote.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quote_line_item_quote_id'), 'quote_line_item', ['quote_id'], unique=False)
    op.create_table('shipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('inquiry_id', sa.Integer(), nullable=False),
    sa.Column('quote_id', sa.Integer(), nullable=False),
    sa.Column('job_number', sa.String(length=40), nullable=False),
    sa.Column('stage', sa.Enum('INQUIRY', 'QUOTED', 'JOB_OPENED', 'DOCS_FILED', 'PICKED_UP', 'IN_TRANSIT', 'CUSTOMS_CLEARANCE', 'ARRIVED', 'DELIVERED', name='shipmentstage', native_enum=False, length=30), nullable=False),
    sa.Column('is_at_risk', sa.Boolean(), nullable=False),
    sa.Column('risk_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['inquiry_id'], ['inquiry.id'], ),
    sa.ForeignKeyConstraint(['quote_id'], ['quote.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quote_id')
    )
    op.create_index(op.f('ix_shipment_customer_id'), 'shipment', ['customer_id'], unique=False)
    op.create_index(op.f('ix_shipment_inquiry_id'), 'shipment', ['inquiry_id'], unique=False)
    op.create_index(op.f('ix_shipment_job_number'), 'shipment', ['job_number'], unique=True)
    op.create_table('shipment_reference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('JOB_NUMBER', 'MAWB', 'HAWB', 'MBL', 'HBL', 'CONTAINER', name='referencetype', native_enum=False, length=30), nullable=False),
    sa.Column('value', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipment.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shipment_id', 'type', 'value', name='uq_shipment_reference_shipment_type_value')
    )
    op.create_index(op.f('ix_shipment_reference_shipment_id'), 'shipment_reference', ['shipment_id'], unique=False)
    op.create_index('ix_shipment_reference_value', 'shipment_reference', ['value'], unique=False)
    op.create_table('status_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.Enum('INQUIRY', 'QUOTED', 'JOB_OPENED', 'DOCS_FILED', 'PICKED_UP', 'IN_TRANSIT', 'CUSTOMS_CLEARANCE', 'ARRIVED', 'DELIVERED', name='shipmentstage', native_enum=False, length=30), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('actor', sa.String(length=120), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('source', sa.Enum('MANUAL', 'AUTOMATED', 'SYSTEM', 'CORRECTION', name='eventsource', native_enum=False, length=30), nullable=False),
    sa.Column('is_stage_change', sa.Boolean(), nullable=False),
    sa.Column('is_internal', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipment.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_status_event_shipment_id'), 'status_event', ['shipment_id'], unique=False)
    op.create_index('ix_status_event_shipment_timestamp', 'status_event', ['shipment_id', 'timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_status_event_shipment_timestamp', table_name='status_event')
    op.drop_index(op.f('ix_status_event_shipment_id'), table_name='status_event')
    op.drop_table('status_event')
    op.drop_index('ix_shipment_reference_value', table_name='shipment_reference')
    op.drop_index(op.f('ix_shipment_reference_shipment_id'), table_name='shipment_reference')
    op.drop_table('shipment_reference')
    op.drop_index(op.f('ix_shipment_job_number'), table_name='shipment')
    op.drop_index(op.f('ix_shipment_inquiry_id'), table_name='shipment')
    op.drop_index(op.f('ix_shipment_customer_id'), table_name='shipment')
    op.drop_table('shipment')
    op.drop_index(op.f('ix_quote_line_item_quote_id'), table_name='quote_line_item')
    op.drop_table('quote_line_item')
    op.drop_index(op.f('ix_quote_inquiry_id'), table_name='quote')
    op.drop_table('quote')
    op.drop_index(op.f('ix_rate_card_charge_rate_card_id'), table_name='rate_card_charge')
    op.drop_table('rate_card_charge')
    op.drop_index(op.f('ix_rate_card_break_rate_card_id'), table_name='rate_card_break')
    op.drop_table('rate_card_break')
    op.drop_index('ix_inquiry_lane_mode', table_name='inquiry')
    op.drop_index(op.f('ix_inquiry_customer_id'), table_name='inquiry')
    op.drop_table('inquiry')
    op.drop_index('ix_rate_card_lane_mode_validity', table_name='rate_card')
    op.drop_table('rate_card')
    op.drop_table('job_number_counter')
    op.drop_index(op.f('ix_customer_email'), table_name='customer')
    op.drop_table('customer')
    # ### end Alembic commands ###
